strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
# type  host           port  user          pass
socks5  YOUR_SERVER_IP 1080  proxy_9b93b2  DTvWPDSk6UeD3HGXiji7
